import { Button, VerticalBox, LineEdit } from "std-widgets.slint";



export component AppWindow inherits Window {
    in property <string> results: "";
    in-out property <bool> open_curtain: false;
    callback device-income(string);
    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Gehalt eingeben";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Ihr Gehalt eingeben";
                height: 35px;
            }
        }

        Row {
            Button {
                text: "Berechnen";
                primary: true;
                height: 35px;
                clicked => {
                    root.open_curtain = !root.open_curtain;
                    device-income(income.text);
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }

                // Left Rectangle
                Rectangle {
                        background: #333333;
                        x: 0px;
                        width: open_curtain ? 0px : (parent.width / 2);
                        height: parent.height;
                        animate width {
                            duration: 250ms;
                            easing: ease-in;
                        }
                    }
                
                // Right Rectangle
                Rectangle {
                        background: #333333;
                        x: open_curtain ? parent.width : (parent.width / 2);
                        width: open_curtain ? 0px : (parent.width / 2);
                        height: parent.height;
                        animate width {
                            duration: 250ms;
                            easing: ease-in;
                        }
                        animate x {
                            duration: 250ms;
                            easing: ease-in;
                        }
                    }
                }
            }
        }
    }
}
