import { Button, VerticalBox, LineEdit } from "std-widgets.slint";



export component AppWindow inherits Window {
    property <string> results: "";
    callback device-income(string);
    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Gehalt eingeben";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Ihr Gehalt eingeben";
                height: 35px;
            }
        }

        Row {
            Button {
                text: "Berechnen";
                primary: true;
                height: 35px;
                clicked => {
                    device-income(income.text);
                }
            }
        }
    }
}
